import * as React from 'react'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter'
import {ThemeProvider} from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import {theme} from './theme'
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript'
import ModeSwitch from '@/app/ModeSwitch'
import {Ubuntu, Ubuntu_Mono} from 'next/font/google'
import {Metadata} from 'next'
import '@fortawesome/fontawesome-free/css/all.min.css'
import '@fortawesome/fontawesome-free/css/brands.min.css'
import '@fortawesome/fontawesome-free/css/solid.min.css'

const ubuntu = Ubuntu({
  weight: '400',
  variable: '--font-ubuntu',
  subsets: ['latin'],
})

const ubuntu_Mono = Ubuntu_Mono({
  weight: '400',
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${ubuntu.variable} ${ubuntu_Mono.variable}`}>
    <InitColorSchemeScript attribute="class"/>
    <AppRouterCacheProvider options={{enableCssLayer: true}}>
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline/>
        <ModeSwitch/>
        {props.children}
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  )
}