import type {Metadata} from 'next'
import {Ubuntu, Ubuntu_Mono} from 'next/font/google'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter'
import {ThemeProvider} from '@mui/material'
import {theme} from '@/app/theme'


const ubuntu = Ubuntu({
  weight: '400',
  variable: '--font-ubuntu',
  subsets: ['latin'],
})

const ubuntu_Mono = Ubuntu_Mono({
  weight: '400',
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${ubuntu.variable} ${ubuntu_Mono.variable}`}>
    <AppRouterCacheProvider
      options={{key: 'css'}}
    >
      <ThemeProvider theme={theme}>
        {children}
      </ThemeProvider>

    </AppRouterCacheProvider>
    </body>
    </html>
  )
}
