import type {Metadata} from 'next'
import {Ubuntu, Ubuntu_Mono} from 'next/font/google'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter'
import {CssBaseline, ThemeProvider} from '@mui/material'
import {defaultTheme} from '@/app/theme'
import {ReactNode} from 'react'
import {AppThemeProvider} from '@/app/theme2'
// import {I18nContextProvider} from '@/app/i18n/I18nContext'


const ubuntu = Ubuntu({
  weight: '400',
  variable: '--font-ubuntu',
  subsets: ['latin'],
})

const ubuntu_Mono = Ubuntu_Mono({
  weight: '400',
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${ubuntu.variable} ${ubuntu_Mono.variable}`}>
    <AppRouterCacheProvider
      options={{key: 'css'}}
    >
      <ThemeProvider theme={defaultTheme}>
        <AppThemeProvider>
          <CssBaseline>
            {children}
          </CssBaseline>
        </AppThemeProvider>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  )
}
